// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_zGkXHRInHuuvD-nItGnDjbmYVh3OPXk',
    appId: '1:917482978563:web:22260685d5c0a35d2fbd36',
    messagingSenderId: '917482978563',
    projectId: 'grand-library-30cbd',
    authDomain: 'grand-library-30cbd.firebaseapp.com',
    storageBucket: 'grand-library-30cbd.firebasestorage.app',
    measurementId: 'G-5VE9WL1DBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB976RfJSec7rEIhOT_OFpBMzMJqNJ--Hg',
    appId: '1:917482978563:android:7b5a882c1cb0a4da2fbd36',
    messagingSenderId: '917482978563',
    projectId: 'grand-library-30cbd',
    storageBucket: 'grand-library-30cbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPed6mGzVgtlOC3XSO_5pBsBM9tHZUoLY',
    appId: '1:917482978563:ios:b24d25f30cb4a9392fbd36',
    messagingSenderId: '917482978563',
    projectId: 'grand-library-30cbd',
    storageBucket: 'grand-library-30cbd.firebasestorage.app',
    iosBundleId: 'com.example.grandLibrary',
  );
}
